#!/bin/sh
var=1
stoploop="$(ls -l *.h | sed '1,3d' | wc -l)"
echo "File :"
echo $file
while [ $var -lt $stoploop ]
do
	file="$(ls -l *.h | awk '{print $9}' | head -n$var | tail -1)"
##	for i in *;
##	do
	echo "$(cat $file | sed '1,12d')" > $file
	echo "Header of $file has been removed"
	var=$((var+1))
	echo "NUMBERS OF LOOPS: $var"
done
